executable = /home/yxiu/Code/NeAT/test_neat.sh
arguments = --gpu 0 --case $(MyArg1)

error = /home/yxiu/Code/NeAT/logs/test_wmask_$(MyArg1).err
output = /home/yxiu/Code/NeAT/logs/test_wmask_$(MyArg1).out
log = /home/yxiu/Code/NeAT/logs/test_wmask_$(MyArg1).log

request_memory = 50000
request_disk = 5G
request_cpus = 8
request_gpus = 1
requirements = (CUDADeviceName=="Quadro RTX 6000" && UtsnameNodename=!="g093" && UtsnameNodename=!="g081")

queue MyArg1 from /home/yxiu/Code/NeuralUDF/raw_lst.txt
