executable = /home/yxiu/Code/NeAT/train_neat.sh
arguments = --case $(MyArg1)

error = /home/yxiu/Code/NeAT/logs/train_wmask_$(MyArg1).err
output = /home/yxiu/Code/NeAT/logs/train_wmask_$(MyArg1).out
log = /home/yxiu/Code/NeAT/logs/train_wmask_$(MyArg1).log

request_memory = 50000
request_disk = 5G
request_cpus = 6
request_gpus = 1
requirements = TARGET.CUDACapability > 7.5
requirements = TARGET.CUDAGlobalMemoryMb > 10000

queue MyArg1 from /home/yxiu/Code/NeAT/train_lst.txt
